logging.level:
  org.zalando.logbook: TRACE
spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driver-class-name: org.h2.Driver
    username: sa
    password: password